services:
  # auth-service:
  #   build: .
  #   environment:
  #     - ConnectionStrings__PostgresConnectionString=${POSTGRES_CONNECTION_STRING}
  #     - JWT_KEY=${JWT_KEY}
  #     - JWT_ISSUER=${JWT_ISSUER}
  #     - JWT_TOKEN_AUDIENCE=${JWT_TOKEN_AUDIENCE}
  #     - ASPNETCORE_URLS=http://+:80
  #   ports:
  #     - 5272:80

  postgres:
    image: postgres
    container_name: postgresDatabase
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
